#!/usr/bin/env python3
# =============================================================================
#  fdny_spawns.py  --  pin FDNY Firefighter victim spawn positions per level
# =============================================================================
#
#  WHAT IT DOES
#  ------------
#  Installs one code cave INSIDE VictimRescueEnt::SpawnAtSpot at 0x0045D717 --
#  after the game has copied the chosen spot's coords and set facing, but
#  BEFORE its own ModelEntity::SnapToFloor call.  For each victim the cave:
#      ord = counter++;  w = want[ord]        (Python fills want[] per map)
#      if w is a valid spot index:
#          overwrite victim.pos (+0x4c/50/54) with spot w's authored coords
#      re-run the game's SnapToFloor on those coords
#  So a forced victim is floor-snapped by the game itself -- no Y guessing,
#  exact every load.  A ring buffer carries {this,blob,count,x,y,z,applied,ord}
#  back to Python purely for logging.
#
#    * MODE = "apply"    ->  Python writes want[ordinal] = the "spot" you set
#                            in spawns.json for each victim (0xFF = leave on
#                            the RNG pick).  The cave does the relocation.
#    * MODE = "capture"  ->  want[] stays all-0xFF (nothing forced); Python
#                            just records which spot the RNG picked, per
#                            victim, into spawns.json.  Play each level once.
#
#  The RNG stream is NOT touched -- the game still draws its spot index; the
#  cave simply substitutes coords before the snap.  Ctrl+C restores the
#  original 7 bytes; vanilla behaviour returns.
#
#  Ordinal sync: Python holds the cave's counter at 0 whenever the ring has
#  been idle for a couple of polls, so each level (re)load's victim burst is
#  numbered from 0 -- works for restarts of the same level too.
#
#  REQUIREMENTS
#  ------------
#    python -m pip install pymem
#    Run this AFTER the game is running (any point -- it takes effect from the
#    next level load).  Run the same bitness of Python as convenient; pymem
#    handles the 32-bit target.  Administrator not normally required, but use
#    an elevated terminal if attach fails with access-denied.
#
#  CONFIG: edit the constants just below, and spawns.json.
#
#  spawns.json is minimal: one map -> a bare list of spot indices, in .bsp
#  spawn order (stable; list position is the victim's identity -- many victims
#  are unnamed "<null>17"). Each entry:
#      N     (int >= 0)  -> force that authored spawn-point index
#                          (0 = editor origin, 1..count-1 = RCS_VictimAltSpot)
#      null  (or < 0)     -> leave that victim on the RNG's pick
#  Nothing else is needed -- no names, no coordinates. An out-of-range index
#  is ignored (victim left on the RNG pick). Which index is which spot: see
#  victims_reference.md (generated by parse_bsp_victims.ps1 alongside a
#  ready-to-edit spawns.generated.json).
#
#      { "<mapname>": [0, 0, null, 2, 0],
#        "<other>":   [] }
#
#  (Back-compat: an entry may also be an object {"spot": N}; older keys on it
#  are ignored.)
# =============================================================================

import json
import logging
import logging.handlers
import os
import struct
import sys
import time
import traceback

try:
    import pymem
except ImportError:
    print("pymem is not installed.  Run:  python -m pip install pymem")
    sys.exit(1)

# ------------------------------ CONFIG ---------------------------------------

PROCESS_NAME = "FDNYFirefighter.exe"
MODE         = "apply"          # "apply" or "capture"
CONFIG_PATH  = os.path.join(os.path.dirname(os.path.abspath(__file__)), "spawns.json")
LOG_PATH     = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fdny_spawns.log")
POLL_MS      = 40              # main-loop poll interval
STOP_ROAM    = True           # also pin FSM state to 4 (idle) so a pinned victim can't wander
EXPECT_BASE  = 0x00400000     # the tool assumes the game module loads here (it does)

# ------------------------- FIXED ADDRESSES (VA) ----------------------------
# From the decompilation.  All VAs; the module has no ASLR so VA == static.

SPAWNATSPOT_VA      = 0x0045D5B0   # VictimRescueEnt::SpawnAtSpot (for reference / probe)
# Hook site is INSIDE SpawnAtSpot, AFTER the xyz record copy + facing, but
# BEFORE the game's own ModelEntity::SnapToFloor call -- so coordinates the
# cave injects here get floor-snapped by the game itself. EBP = victim `this`.
#   0045d717  8B CD              MOV ECX,EBP            } displaced (7 bytes);
#   0045d719  E8 E2 02 04 00     CALL 0x0049DA00       } re-emitted by the cave
#   0045d71e  ...                                       <- re-entry
CAVE_PATCH_VA       = 0x0045D717
CAVE_PATCH_ORIG     = bytes.fromhex("8BCDE8E2020400")         # MOV ECX,EBP ; CALL SnapToFloor (7 bytes)
CAVE_REENTRY_VA     = 0x0045D71E
SNAPTOFLOOR_VA      = 0x0049DA00   # ModelEntity::SnapToFloor(this in ECX) -- re-run by the cave

VICTIM_VTABLE_VA    = 0x004E25B8   # VictimRescueEnt primary vtable (sanity check: *(this) == this)
GSESSION_PTR_VA     = 0x00502AAC   # g_session = *(void**)0x00502AAC
GSESSION_TLI_OFF    = 0x688        # g_session + 0x688  -> active TLevelInfo*

# victim entity field offsets (from the operator-new(0x22c) base = `this`)
OFF_DEFBLOB   = 0x150   # -> geEntity user-data blob (0x34 bytes)
OFF_FSMSTATE  = 0x120   # int: 4 idle, 5 carried, 6 claimed, 7 roaming
OFF_SPOTARR   = 0x200   # -> pointer to the array of spot-record pointers
OFF_SPOTCOUNT = 0x204   # int
OFF_POS_X     = 0x4C    # float
OFF_POS_Y     = 0x50
OFF_POS_Z     = 0x54
# def-blob field offsets
BLOB_NAME_OFF = 0x10    # -> raw char*  (the entity name keyvalue)
BLOB_TYPE_OFF = 0x14    # -> raw char*  (the type-name keyvalue: girl/man/...)
# TLevelInfo field offsets
TLI_MAPNAME   = 0x00    # String (COW): object is 1 ptr; chars at *(ptr)+0x0C
TLI_INDEX_A   = 0x1C    # preferred sequential index (if > 0)
TLI_INDEX_B   = 0x18
STRING_CHARS  = 0x0C    # RatStr: +0 refcnt, +4 len, +8 bufsize, +0xC chars

# --------------------------- cave memory layout ---------------------------- #
#   +0x000  code
#   +CTR_O  u32   ordinal counter -- ++ per VictimRescueEnt::SpawnAtSpot call.
#                 Python keeps it 0 during quiet periods (see quiet-detect in
#                 the main loop); the cave counts up through a spawn burst.
#   +TAB_O  64 x u8  want[ordinal]: spot index to force, 0xFF = leave on RNG.
#                 Python rewrites this every poll for the current map.
#   +HEAD_O u32   ring write cursor
#   +DATA_O RING_CAP x SLOT_SIZE  observation ring (logging only)
RING_CAP    = 64
TAB_LEN     = 64
SLOT_SIZE   = 32     # {this,blob,count, x,y,z, appliedSpot:i32, ordinal:u32}
CODE_MAX    = 0x140
CTR_O       = CODE_MAX
TAB_O       = CTR_O + 4
HEAD_O      = TAB_O + TAB_LEN
DATA_O      = HEAD_O + 4
ALLOC_SIZE  = DATA_O + RING_CAP * SLOT_SIZE
LEAVE       = 0xFF   # want[] sentinel: don't relocate this victim

# --------------------------------------------------------------------------- #


def setup_logging():
    log = logging.getLogger("fdny")
    log.setLevel(logging.DEBUG)
    fmt = logging.Formatter("%(asctime)s %(levelname)-5s %(message)s", "%H:%M:%S")
    sh = logging.StreamHandler(sys.stdout)
    sh.setFormatter(fmt)
    log.addHandler(sh)
    try:
        fh = logging.handlers.RotatingFileHandler(LOG_PATH, maxBytes=1_000_000, backupCount=3, encoding="utf-8")
        fh.setFormatter(fmt)
        log.addHandler(fh)
    except OSError as e:
        log.warning("could not open log file %s: %s (console only)", LOG_PATH, e)
    return log


log = setup_logging()


# ----------------------------- shellcode ----------------------------------- #

def emit_cave(cave_base: int) -> bytes:
    """Assemble the relocation cave. Hooked at 0x0045d717, EBP = victim `this`,
    right before SpawnAtSpot's own SnapToFloor call.

      ord = [CTR]; [CTR] = ord + 1
      w   = want[ord]                       (0xFF or ord>=64 -> leave alone)
      if w < [ebp+0x204]:
          rec = (*(ebp+0x200))[w]
          [ebp+0x4c/0x50/0x54] = rec.x/y/z        <-- inject authored coords
      ring <- {this, blob, count, x, y, z, appliedSpot, ord}
      MOV ECX,EBP ; CALL SnapToFloor            <-- displaced; game snaps OUR coords
      JMP 0x0045d71e
    """
    ctr, tab, head, data = (cave_base + o for o in (CTR_O, TAB_O, HEAD_O, DATA_O))
    b = bytearray()
    fixups = []                                    # (index_of_rel8_byte,) -> patched to Ldone

    def jshort(op):                                # emit `op rel8` targeting Ldone
        b.extend(op)
        fixups.append(len(b))
        b.append(0)

    b += b"\x9C\x60"                                       # pushfd ; pushad
    b += b"\x8B\x35" + struct.pack("<I", ctr)              # mov esi, [CTR]      ; esi = ordinal
    b += b"\x8D\x46\x01"                                   # lea eax, [esi+1]
    b += b"\xA3" + struct.pack("<I", ctr)                  # mov [CTR], eax
    b += b"\xBF\xFF\xFF\xFF\xFF"                           # mov edi, -1         ; appliedSpot
    b += b"\x83\xFE\x40"; jshort(b"\x73")                  # cmp esi,64 ; jae Ldone
    b += b"\xBB" + struct.pack("<I", tab)                  # mov ebx, TAB
    b += b"\x0F\xB6\x04\x33"                               # movzx eax, byte [ebx+esi]  ; want
    b += b"\x3C\xFF"; jshort(b"\x74")                      # cmp al,0xFF ; je Ldone
    b += b"\x3B\x85" + struct.pack("<i", OFF_SPOTCOUNT)    # cmp eax, [ebp+0x204]
    jshort(b"\x73")                                        # jae Ldone
    b += b"\x8B\x8D" + struct.pack("<i", OFF_SPOTARR)      # mov ecx, [ebp+0x200] ; array base
    b += b"\x8B\x0C\x81"                                   # mov ecx, [ecx+eax*4] ; rec ptr
    b += b"\x85\xC9"; jshort(b"\x74")                      # test ecx,ecx ; je Ldone
    b += b"\x8B\xF8"                                       # mov edi, eax        ; appliedSpot = want
    b += b"\x8B\x11"       + b"\x89\x55" + bytes([OFF_POS_X])   # mov edx,[ecx]   ; mov [ebp+0x4c],edx
    b += b"\x8B\x51\x04"   + b"\x89\x55" + bytes([OFF_POS_Y])   # mov edx,[ecx+4] ; mov [ebp+0x50],edx
    b += b"\x8B\x51\x08"   + b"\x89\x55" + bytes([OFF_POS_Z])   # mov edx,[ecx+8] ; mov [ebp+0x54],edx
    # ---- Ldone: write the observation ring record ----
    ldone = len(b)
    for idx in fixups:
        rel = ldone - (idx + 1)
        assert 0 <= rel < 128, "cave short-jump out of range (%d)" % rel
        b[idx] = rel
    b += b"\xA1" + struct.pack("<I", head)                 # mov eax, [HEAD]
    b += b"\x6B\xC8" + bytes([SLOT_SIZE])                  # imul ecx, eax, SLOT_SIZE
    b += b"\xBA" + struct.pack("<I", data)                 # mov edx, DATA
    b += b"\x01\xCA"                                       # add edx, ecx        ; edx -> slot
    b += b"\x89\x2A"                                       # mov [edx], ebp      ; this
    b += b"\x8B\x8D" + struct.pack("<i", OFF_DEFBLOB) + b"\x89\x4A\x04"     # blob  -> slot+4
    b += b"\x8B\x8D" + struct.pack("<i", OFF_SPOTCOUNT) + b"\x89\x4A\x08"   # count -> slot+8
    b += b"\x8B\x4D" + bytes([OFF_POS_X]) + b"\x89\x4A\x0C"                 # x     -> slot+12
    b += b"\x8B\x4D" + bytes([OFF_POS_Y]) + b"\x89\x4A\x10"                 # y     -> slot+16
    b += b"\x8B\x4D" + bytes([OFF_POS_Z]) + b"\x89\x4A\x14"                 # z     -> slot+20
    b += b"\x89\x7A\x18"                                   # mov [edx+24], edi   ; appliedSpot
    b += b"\x89\x72\x1C"                                   # mov [edx+28], esi   ; ordinal
    b += b"\x40\x83\xE0" + bytes([RING_CAP - 1])           # inc eax ; and eax, 63
    b += b"\xA3" + struct.pack("<I", head)                 # mov [HEAD], eax
    b += b"\x61\x9D"                                       # popad ; popfd
    # ---- re-emit displaced (MOV ECX,EBP ; CALL SnapToFloor), then jmp back ----
    b += b"\x8B\xCD"                                       # mov ecx, ebp
    b += b"\xE8" + struct.pack("<i", SNAPTOFLOOR_VA - (cave_base + len(b) + 5))   # call SnapToFloor
    b += b"\xE9" + struct.pack("<i", CAVE_REENTRY_VA - (cave_base + len(b) + 5))  # jmp 0x0045d71e
    if len(b) > CODE_MAX:
        raise RuntimeError("cave code overflow (%d > %d)" % (len(b), CODE_MAX))
    return bytes(b)


# ----------------------------- helpers ------------------------------------- #

class Mem:
    def __init__(self, pm): self.pm = pm
    def u32(self, a):   return self.pm.read_uint(a)
    def i32(self, a):   return struct.unpack("<i", self.pm.read_bytes(a, 4))[0]
    def f32(self, a):   return struct.unpack("<f", self.pm.read_bytes(a, 4))[0]
    def wf32(self, a, v): self.pm.write_bytes(a, struct.pack("<f", float(v)), 4)
    def wi32(self, a, v): self.pm.write_bytes(a, struct.pack("<i", int(v)), 4)
    def cstr(self, a, n=128):
        if not a: return ""
        try:
            raw = self.pm.read_bytes(a, n)
        except Exception:
            return ""
        z = raw.find(b"\x00")
        return raw[: z if z >= 0 else n].decode("latin-1", "replace")


def load_config():
    if not os.path.exists(CONFIG_PATH):
        return {}
    try:
        # utf-8-sig: transparently strips a BOM if the editor / PowerShell added one
        with open(CONFIG_PATH, "r", encoding="utf-8-sig") as f:
            return json.load(f)
    except Exception as e:
        log.error("could not read %s: %s -- treating as empty", CONFIG_PATH, e)
        return {}


def save_config(cfg):
    tmp = CONFIG_PATH + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2, sort_keys=True)
    os.replace(tmp, CONFIG_PATH)


def read_spots(mem, this_):
    """Every authored spawn spot for a victim, read live from the game.
       victim+0x200 -> array of `count` pointers, each -> {float x,y,z,angle}.
       Returns list[(x, y, z)] (index 0 = editor origin), or []."""
    try:
        count = mem.i32(this_ + OFF_SPOTCOUNT)
        if count <= 0 or count > 64:
            return []
        arr = mem.u32(this_ + OFF_SPOTARR)
        if not arr:
            return []
        out = []
        for i in range(count):
            rec = mem.u32(arr + i * 4)
            if not rec:
                out.append(None)
                continue
            out.append((mem.f32(rec), mem.f32(rec + 4), mem.f32(rec + 8)))
        return out
    except Exception:
        return []


def match_spot_index(spots, pos):
    """Which spot index produced `pos`?  SpawnAtSpot copies spots[idx] verbatim
       then SnapToFloor nudges only Y -- so x and z match exactly."""
    for i, s in enumerate(spots):
        if s and abs(s[0] - pos[0]) < 0.01 and abs(s[2] - pos[2]) < 0.01:
            return i
    return -1


# ------------------------------- main ------------------------------------- #

def main():
    log.info("attach   opening %s ...", PROCESS_NAME)
    try:
        pm = pymem.Pymem(PROCESS_NAME)
    except Exception as e:
        log.error("attach   FAILED: %s", e)
        log.error("         is the game running?  try an elevated terminal.")
        return 2

    base = pm.base_address
    log.info("attach   pid=%d  module base=0x%08X", pm.process_id, base)
    if base != EXPECT_BASE:
        log.error("attach   module base 0x%08X != expected 0x%08X -- addresses would be wrong. ABORT.",
                  base, EXPECT_BASE)
        return 3

    mem = Mem(pm)

    # ---- probe: verify the patch site looks like the expected build ----
    here = pm.read_bytes(CAVE_PATCH_VA, len(CAVE_PATCH_ORIG))
    if here == CAVE_PATCH_ORIG:
        log.info("probe    0x%08X ok  (%s)", CAVE_PATCH_VA, CAVE_PATCH_ORIG.hex())
    elif here[:1] == b"\xE9":
        log.error("probe    0x%08X already contains a JMP -- tool already running? ABORT.", CAVE_PATCH_VA)
        return 4
    else:
        log.error("probe    0x%08X = %s, expected %s -- wrong game build/version. ABORT.",
                  CAVE_PATCH_VA, here.hex(), CAVE_PATCH_ORIG.hex())
        return 4

    # ---- allocate + install ----
    cave = pm.allocate(ALLOC_SIZE)
    log.info("cave     allocated 0x%08X  (%d bytes: %d code / ctr 0x%X / table 0x%X / ring 0x%X x %d)",
             cave, ALLOC_SIZE, CODE_MAX, cave + CTR_O, cave + TAB_O, cave + DATA_O, RING_CAP)
    pm.write_bytes(cave + CTR_O, b"\x00" * (4 + TAB_LEN + 4), 4 + TAB_LEN + 4)   # ctr, table (all 0), head
    pm.write_bytes(cave + TAB_O, bytes([LEAVE]) * TAB_LEN, TAB_LEN)              # table -> all "leave"
    code = emit_cave(cave)
    pm.write_bytes(cave, code, len(code))
    log.info("cave     wrote %d code bytes", len(code))

    jmp_rel = cave - (CAVE_PATCH_VA + 5)
    patch = b"\xE9" + struct.pack("<i", jmp_rel) + b"\x90" * (len(CAVE_PATCH_ORIG) - 5)
    pm.write_bytes(CAVE_PATCH_VA, patch, len(patch))
    log.info("hook     0x%08X -> jmp 0x%08X   (patch %s, %d bytes displaced)",
             CAVE_PATCH_VA, cave, patch.hex(), len(CAVE_PATCH_ORIG))
    log.info("run      MODE=%s  config=%s  poll=%dms  stop_roam=%s", MODE, CONFIG_PATH, POLL_MS, STOP_ROAM)
    log.info("run      the cave relocates victims IN-PLACE before the game's own SnapToFloor;")
    log.info("run      Ctrl+C to stop and restore the original bytes.")

    cfg = load_config()
    tail       = mem.u32(cave + HEAD_O)   # ignore anything already in the ring
    cur_map    = None
    prev_head  = mem.u32(cave + HEAD_O)
    quiet      = 0                         # consecutive polls with the ring drained AND idle
    tbl_map    = None                      # which map's config is currently written to the cave table
    settle     = []                        # [(deadline_ts, this, tag)] -> re-read final pos and log

    try:
        while True:
            time.sleep(POLL_MS / 1000.0)

            # ---- current level ----
            try:
                gs = mem.u32(GSESSION_PTR_VA)
                tli = mem.u32(gs + GSESSION_TLI_OFF) if gs else 0
                mapname, lvlidx = "", None
                if tli:
                    sp = mem.u32(tli + TLI_MAPNAME)
                    mapname = mem.cstr(sp + STRING_CHARS) if sp else ""
                    a = mem.i32(tli + TLI_INDEX_A)
                    lvlidx = a if a > 0 else mem.i32(tli + TLI_INDEX_B)
            except Exception:
                mapname, lvlidx = "", None

            if mapname and mapname != cur_map:
                cur_map = mapname
                lst = cfg.get(cur_map, [])
                have = sum(1 for e in lst if e)
                log.info("level    map='%s'  index=%s  (%d victim entr%s in config)",
                         cur_map, lvlidx, have, "y" if have == 1 else "ies")

            # ---- keep the cave's want-table current for this map ----
            # written on every map change, well before that map's victims spawn.
            if cur_map != tbl_map and cur_map is not None:
                tbl = bytearray([LEAVE]) * TAB_LEN
                if MODE == "apply":
                    for i, ent in enumerate(cfg.get(cur_map, [])):
                        if i >= TAB_LEN:
                            break
                        sp = ent.get("spot") if isinstance(ent, dict) else ent
                        if isinstance(sp, int) and 0 <= sp < LEAVE:
                            tbl[i] = sp
                try:
                    pm.write_bytes(cave + TAB_O, bytes(tbl), TAB_LEN)
                    tbl_map = cur_map
                    forced = ["#%d->spot%d" % (i, v) for i, v in enumerate(tbl) if v != LEAVE]
                    log.info("table    map='%s'  pinned: %s", cur_map, ", ".join(forced) or "(none)")
                except Exception as e:
                    log.error("table    write failed: %s", e)

            # ---- hold the cave's ordinal counter at 0 while nothing is spawning ----
            # so the next level (re)load's burst is counted from 0. During a burst
            # the ring head advances, so we back off and let the cave count up.
            head = mem.u32(cave + HEAD_O)
            if head == tail and head == prev_head:
                quiet += 1
                if quiet >= 2:                       # ring idle 2+ polls -> safe to reset
                    try: pm.write_bytes(cave + CTR_O, b"\x00\x00\x00\x00", 4)
                    except Exception: pass
            else:
                quiet = 0
            prev_head = head

            # ---- drain the observation ring (the cave already did the moving) ----
            n = (head - tail) % RING_CAP
            for ri in range(n):
                slot = cave + DATA_O + tail * SLOT_SIZE
                tail = (tail + 1) % RING_CAP
                try:
                    this_   = mem.u32(slot)
                    blob    = mem.u32(slot + 4)
                    count   = mem.i32(slot + 8)
                    x, y, z = mem.f32(slot + 12), mem.f32(slot + 16), mem.f32(slot + 20)
                    applied = mem.i32(slot + 24)
                    ordn    = mem.u32(slot + 28)
                    name    = mem.cstr(mem.u32(blob + BLOB_NAME_OFF)) if blob else "?"
                    vtype   = mem.cstr(mem.u32(blob + BLOB_TYPE_OFF)) if blob else ""
                except Exception:
                    log.warning("spawn    (unreadable ring slot -- skipped)")
                    continue

                if ordn >= TAB_LEN:
                    log.warning("spawn    ord=%d out of range (counter not reset in time?) -- reload the level", ordn)
                    continue

                spots  = read_spots(mem, this_)
                picked = match_spot_index(spots, (x, y, z))   # pos here = chosen spot's authored coords

                if applied >= 0:
                    log.info("spawn    ord=%d  '%s' (%s)  count=%d  -> FORCED spot %d  (game floor-snaps it)  this=0x%08X",
                             ordn, name, vtype, count, applied, this_)
                else:
                    log.info("spawn    ord=%d  '%s' (%s)  count=%d  RNG spot %s  (not pinned)  this=0x%08X",
                             ordn, name, vtype, count, picked if picked >= 0 else "?", this_)

                if MODE == "capture":
                    m = cfg.setdefault(cur_map or "?", [])
                    while len(m) <= ordn:
                        m.append(None)
                    if m[ordn] != picked and picked >= 0:
                        m[ordn] = picked
                        try:
                            save_config(cfg)
                            log.info("capture  map='%s' ord=%d '%s'  spot=%d/%d  (saved)",
                                     cur_map, ordn, name, picked, count)
                        except Exception as e:
                            log.error("capture  save failed: %s", e)
                    continue

                # apply mode -- the cave already relocated. Follow-ups only.
                lst = cfg.get(cur_map or "", [])
                ent = lst[ordn] if ordn < len(lst) else None
                cfg_spot = ent.get("spot") if isinstance(ent, dict) else ent
                if applied >= 0:
                    if STOP_ROAM:
                        try: mem.wi32(this_ + OFF_FSMSTATE, 4)
                        except Exception: pass
                    settle.append((time.time() + 0.30, this_, "ord=%d '%s' spot %d" % (ordn, name, applied)))
                elif isinstance(cfg_spot, int) and cfg_spot >= 0:
                    log.warning("spawn    ord=%d '%s'  config wants spot %d but the cave did NOT force it "
                                "(want-table not in place yet, or index >= count %d) -- reload the level",
                                ordn, name, cfg_spot, count)

            # ---- report where pinned victims landed once SnapToFloor has run ----
            if settle:
                now = time.time()
                still = []
                for deadline, this_, tag in settle:
                    if now < deadline:
                        still.append((deadline, this_, tag)); continue
                    try:
                        log.info("settled  %s  -> (%.1f, %.1f, %.1f)", tag,
                                 mem.f32(this_ + OFF_POS_X), mem.f32(this_ + OFF_POS_Y), mem.f32(this_ + OFF_POS_Z))
                    except Exception:
                        pass
                settle = still

    except KeyboardInterrupt:
        log.info("stop     Ctrl+C")
    except Exception:
        log.error("stop     unhandled exception:\n%s", traceback.format_exc())
    finally:
        try:
            pm.write_bytes(CAVE_PATCH_VA, CAVE_PATCH_ORIG, len(CAVE_PATCH_ORIG))
            log.info("cleanup  restored original bytes at 0x%08X", CAVE_PATCH_VA)
        except Exception as e:
            log.error("cleanup  FAILED to restore 0x%08X (%s) -- game may crash on next victim spawn!",
                      CAVE_PATCH_VA, e)
        try:
            pm.free(cave)
            log.info("cleanup  freed cave 0x%08X", cave)
        except Exception:
            pass
        log.info("done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
